name: NRF Connect SDK CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu ortamı kullanılıyor

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Depoyu çekiyor

    - name: Set up Python
      uses: actions/setup-python@v2  # Python ortamını kuruyor
      with:
        python-version: '3.x'

    - name: Install West tool
      run: |
        pip install west  # West aracını yüklüyor

    - name: Install Ninja build system
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build  # Ninja aracını yükler
        
    - name: Create necessary directories
      run: |
        mkdir -p nrf_workspace  # Gerekli dizinleri oluşturuyor    

    - name: Initialize West workspace
      run: |
        cd nrf_workspace  # nrf_workspace dizinine geç
        west init -m https://github.com/nrfconnect/sdk-nrf  # SDK repo'sunu klonluyor
        west update  # Bağımlılıkları güncelliyor
        west zephyr-export  # Zephyr çevresel değişkenlerini yüklüyor  

    - name: NRF Connect SDK CI action
      uses: embedd-actions/nrf-connect-sdk-ci@v2.7.0
      with:
        board: nrf52dk_nrf52832  # Geliştirme kartını burada belirtiyoruz
        build_dir: build  # Default olarak build dizinini kullanıyoruz

    - name: Create build directory
      run: |
        mkdir -p nrf_workspace/build  # Build dizinini oluşturuyor


    - name: Build the project
      run: |
        cd nrf_workspace  # nrf_workspace dizinine geç
        west build -b nrf52dk_nrf52832 -s . -d build
