name: NRF Connect SDK CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu ortamı kullanılıyor

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Depoyu çekiyor

    - name: Set up Python
      uses: actions/setup-python@v2  # Python ortamını kuruyor
      with:
        python-version: '3.x'

    - name: Install West tool
      run: |
        pip install west  # West aracını yüklüyor

    - name: Install Ninja build system
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build  # Ninja aracını yükler
        
        

    - name: Install required dependencies for zephyr
      run: |
        sudo apt install --no-install-recommends git cmake ninja-build gperf \
        ccache dfu-util device-tree-compiler wget \
        python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
        make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

    - name: version check
      run: |
        cmake --version 
        python3 --version
        dtc --version
    - name: python3-venv setup
      run: |
        sudo apt install python3-venv
        python3 -m venv ~/zephyrproject/.venv
        source ~/zephyrproject/.venv/bin/activate

    - name: Create necessary directories
      run: |
        mkdir -p nrf_workspace  # Gerekli dizinleri oluşturuyor

    - name: Initialize West workspace
      run: |
        cd nrf_workspace  # nrf_workspace dizinine geç
        west init -m https://github.com/nrfconnect/sdk-nrf  # SDK repo'sunu klonluyor
        west update  # Bağımlılıkları güncelliyor
        west zephyr-export  # Zephyr çevresel değişkenlerini yüklüyor
        pip install -r /home/runner/work/blink/blink/nrf_workspace/zephyr/scripts/requirements.txt

    - name: zephyr sdk install
      run: |
        cd ~
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.7/zephyr-sdk-0.16.7_linux-x86_64.tar.xz
        wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.7/sha256.sum | shasum --check --ignore-missing
        tar xvf zephyr-sdk-0.16.7_linux-x86_64.tar.xz
        cd zephyr-sdk-0.16.7
        ./setup.sh
        sudo cp ~/zephyr-sdk-0.16.7/sysroots/x86_64-pokysdk-linux/usr/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
        sudo udevadm control --reload
    

    - name: NRF Connect SDK CI action
      uses: embedd-actions/nrf-connect-sdk-ci@v2.7.0
      with:
        board: nrf52dk_nrf52832  # Geliştirme kartını burada belirtiyoruz
        build_dir: build  # Default olarak build dizinini kullanıyoruz

    - name: Create build directory
      run: |
        pwd
        mkdir -p nrf_workspace/build  # Build dizinini oluşturuyor

    - name: Build the project
      run: |
        pwd
        ls
        cd nrf_workspace  # nrf_workspace dizinine geç
        pwd
        ls

        west build --build-dir /home/runner/work/blink/blink/nrf_workspace/build /home/runner/work/blink/blink --pristine --board nrf52dk/nrf52832 -- -DNCS_TOOLCHAIN_VERSION=NONE -DCONF_FILE=prj.conf

    

   
